---
- name: Configuring apache2 uisng child playbooks
  hosts: all
  tasks:
   - name: Call multiple child playbooks
     include: "{{item}}"
     with_items:
      - install_apache.yml
      - edit_index.yml
      - restart.yml
      - check_url_response.yml
...
