---
- name: Download docker images
  hosts: all
  tasks:
   - name: Download images
     docker_image:
      name: "{{item}}"
     with_items:
      - tomcat
      - httpd
      - nginx
      - jenkins
...
