---
- name: Create jenkins ci-cd setup uisng Ansible and Docker
  hosts: all
  tasks:
   - name: Create a jenkins container
     docker_container:
      image: jenkins
      name: myjenkins
      ports:
       - 5050:8080

   - name: Create a tomcat container as QAServer and ProdServer
     docker_container:
      image: tomcat
      name: "{{item.a}}"
      ports:
       - "{{item.b}}"
      links:
       - myjenkins:jenkins
     with_items:
      - {a: qaserver,b: "6060:8080"}
      - {a: prodserver,b: "7070:8080"}

