---
- name: Create an ubuntu container and mount a volume on it
  hosts: all
  tasks:
   - name: Create ubuntu container
     docker_container:
      image: ubuntu
      name: myubuntu
      interactive: yes
      tty: yes
      volumes:
       - /data
