---
- name: Install multiple s/w
  hosts: all
  tasks:
   - name: Install s/w's
     apt:
      name: ['git', 'tree', 'maven']
      state: ['present','absent','latest']
      update_cache: ['no','no','yes']

