---
- name: Setup of Docker for Ansible-Docker integrations
  hosts: all
  tasks:
   - name: Install python pip
     apt:
      name: python3-pip
      state: present
      update_cache: yes
   - name: Download the shell script and install docker,docker-py
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip3 install docker-py
