---
- name: Configuring tomcat9
  hosts: all
  tasks:
   - name: Install tomcat9
     apt:
      name: tomcat9
      state: present
   - name: Copy the tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat
   - name: Change the port of tomcat from 8080 to 9090
     replace:
      regexp: 8080
      replace: 9090
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9
     service:
      name: tomcat9
      state: restarted
   - name: Pause for 5 mins
     pause:
      minutes: 5
   - name: Check url response of server1 
     uri:
      url: http://172.31.16.35:9090
      status_code: 200
   - name: Check url response of server2
     uri:
      url: http://172.31.18.87:9090
      status_code: 200
...
