---
- name: Install required s/w's for ci-cd
  hosts: all
  tasks:
   - block: 
      - name: Install s/w's
        apt:
         name: "{{item.a}}"
         state: present
         update_cache: "{{item.b}}"
        with_items:
         - {a: git,b: yes}
         - {a: openjdk-8-jdk,b: no}
         - {a: maven,b: no}
         - {a: tomcat9,b: no}
         - {a: tomcat9-admin,b: no}
     rescue:
      - name: Send email to Devops team
        mail:
         host: localhost
         port: 25
         to: devops.admin@oultook.com
         subject: Setup Failed
         body: Installtion of s/w's for ci-cd has failed
...


